package controllers

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"time"
	"web/services/assets/models"
)

func (c *Construct) getAssignCohorts(userID uint64, roleName string) []uint64 {
	var cohortIDs []uint64

	switch roleName {
	case "Mentor":
		c.DB.Table("cohort_mentors").
			Select("cohort_id").
			Where("mentor_id = ?", userID).
			Scan(&cohortIDs)
	case "Supervisor":
		c.DB.Table("cohort_supervisors").
			Select("cohort_id").
			Where("supervisor_id = ?", userID).
			Scan(&cohortIDs)
	}

	return cohortIDs
}

// reports weekly generated by students

func (c *Construct) CreateWeeklyReport(w http.ResponseWriter, r *http.Request) {
	var input models.WeeklyReport
	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
		c.Json(w, http.StatusBadRequest, "Invalid request body", nil)
		return
	}

	user, err := c.GetAuthenticatedUser(r)
	if err != nil {
		c.Json(w, http.StatusUnauthorized, "Unauthorized", nil)
		return
	}

	// Set student info and initial status
	input.StudentID = user.UserID
	input.Status = "Pending"
	now := time.Now()
	input.CreatedAt = now
	input.UpdatedAt = now

	// Save the weekly report
	if err := c.DB.Create(&input).Error; err != nil {
		c.Json(w, http.StatusInternalServerError, "Failed to create report", map[string]interface{}{
			"error": err.Error(),
		})
		return
	}

	// 🔔 Notify and Track: Student confirmation
	c.NotifyAndTrack(
		user.UserID,
		"Weekly Report Submitted",
		fmt.Sprintf("Your weekly report for week %s - %s has been submitted successfully.",
			input.WeekStart.Format("02 Jan"), input.WeekEnd.Format("02 Jan")),
		"Weekly Report Submission",
		"WeeklyReport",
		&input.ID,
		"Pending",
	)

	// 🔔 Notify all mentors/supervisors of the same cohort
	var supervisors []models.User
	c.DB.Joins("JOIN cohort_supervisors cs ON cs.supervisor_id = users.user_id").
		Where("cs.cohort_id = ?", input.CohortID).
		Find(&supervisors)

	for _, sup := range supervisors {
		c.NotifyAndTrack(
			sup.UserID,
			"New Weekly Report Submitted",
			fmt.Sprintf("A new weekly report from %s is available for viewing.", user.Username),
			"Weekly Report Review",
			"WeeklyReport",
			&input.ID,
			"Pending",
		)
	}

	// ✅ Return response without Comments (use empty list for comments if desired)
	c.Json(w, http.StatusCreated, "Weekly report submitted successfully", map[string]interface{}{
		"data": map[string]interface{}{
			"id":          input.ID,
			"student_id":  input.StudentID,
			"cohort_id":   input.CohortID,
			"status":      input.Status,
			"linked_item": input.LinkedItemID,
			"week_start":  input.WeekStart,
			"week_end":    input.WeekEnd,
			"created_at":  input.CreatedAt,
			"updated_at":  input.UpdatedAt,
			"comments":    []interface{}{}, // empty list initially
		},
	})
}

// updating weekly reports

func (c *Construct) UpdateWeeklyReport(w http.ResponseWriter, r *http.Request) {
	// Get report ID from URL query
	idStr := r.URL.Query().Get("id")
	if idStr == "" {
		c.Json(w, http.StatusBadRequest, "Report ID is required", nil)
		return
	}
	reportID, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Json(w, http.StatusBadRequest, "Invalid report ID", nil)
		return
	}

	// Authenticated user
	user, err := c.GetAuthenticatedUser(r)
	if err != nil {
		c.Json(w, http.StatusUnauthorized, "Unauthorized", nil)
		return
	}

	// Fetch report with comments and student info
	var report models.WeeklyReport
	if err := c.DB.Preload("Comments.User.Profile").
		Preload("Student").
		First(&report, reportID).Error; err != nil {
		c.Json(w, http.StatusNotFound, "Report not found", nil)
		return
	}

	// Check cohort access: only allow users in the same cohort
	if !c.UserHasCohortAccess(user.UserID, *report.CohortID) {
		c.Json(w, http.StatusForbidden, "You do not have access to this report", nil)
		return
	}

	// Parse input
	var input struct {
		WorkDone    *string `json:"work_done,omitempty"`
		PlannedWork *string `json:"planned_work,omitempty"`
		NextWeek    *string `json:"next_week,omitempty"`
		Challenges  *string `json:"challenges,omitempty"`
		Comment     *string `json:"comment,omitempty"` // optional comment
	}
	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
		c.Json(w, http.StatusBadRequest, "Invalid input", nil)
		return
	}

	updated := false

	// Only the report owner can update work fields
	if report.StudentID == user.UserID {
		if input.WorkDone != nil {
			report.WorkDone = *input.WorkDone
			updated = true
		}
		if input.PlannedWork != nil {
			report.PlannedWork = *input.PlannedWork
			updated = true
		}
		if input.NextWeek != nil {
			report.NextWeek = *input.NextWeek
			updated = true
		}
		if input.Challenges != nil {
			report.Challenges = *input.Challenges
			updated = true
		}
	}

	// Add comment if provided (any cohort member)
	if input.Comment != nil && *input.Comment != "" {
		comment := models.WeeklyReportComment{
			ReportID:  report.ID,
			UserID:    user.UserID,
			Comment:   *input.Comment,
			CreatedAt: time.Now(),
		}
		if err := c.DB.Create(&comment).Error; err != nil {
			c.Json(w, http.StatusInternalServerError, "Failed to add comment", map[string]interface{}{"error": err.Error()})
			return
		}
		updated = true

		// Notify report owner if commenter is not the owner
		if report.StudentID != user.UserID {
			c.NotifyAndTrack(
				report.StudentID,
				"New Comment on Weekly Report",
				fmt.Sprintf("%s commented on your weekly report: %s", user.Username, *input.Comment),
				"Comment",
				"WeeklyReport",
				&report.ID,
				"Commented",
			)
		}
	}

	// Save report if any changes
	if updated {
		report.UpdatedAt = time.Now()
		if err := c.DB.Save(&report).Error; err != nil {
			c.Json(w, http.StatusInternalServerError, "Failed to update report", map[string]interface{}{"error": err.Error()})
			return
		}
	}

	// Fetch updated report with comments for response
	if err := c.DB.Preload("Comments.User.Profile").
		Preload("Student").
		First(&report, report.ID).Error; err != nil {
		c.Json(w, http.StatusInternalServerError, "Failed to fetch updated report", map[string]interface{}{"error": err.Error()})
		return
	}

	c.Json(w, http.StatusOK, "Weekly report updated successfully", map[string]interface{}{
		"data": report,
	})
}

// adding comments on reports

func (c *Construct) AddReportComment(w http.ResponseWriter, r *http.Request) {
	// 1️⃣ Get report ID from URL
	idStr := r.URL.Query().Get("id")
	if idStr == "" {
		c.Json(w, http.StatusBadRequest, "Report ID is required", nil)
		return
	}
	reportID, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Json(w, http.StatusBadRequest, "Invalid report ID", nil)
		return
	}

	// 2️⃣ Parse comment input
	var input struct {
		Comment string `json:"comment"`
	}
	if err := json.NewDecoder(r.Body).Decode(&input); err != nil || input.Comment == "" {
		c.Json(w, http.StatusBadRequest, "Invalid input, comment is required", nil)
		return
	}

	// 3️⃣ Authenticate user
	user, err := c.GetAuthenticatedUser(r)
	if err != nil {
		c.Json(w, http.StatusUnauthorized, "Unauthorized", nil)
		return
	}

	// 4️⃣ Fetch the report
	var report models.WeeklyReport
	if err := c.DB.Preload("Student").First(&report, reportID).Error; err != nil {
		c.Json(w, http.StatusNotFound, "Report not found", nil)
		return
	}

	// 5️⃣ Check cohort access
	if !c.UserHasCohortAccess(user.UserID, *report.CohortID) {
		c.Json(w, http.StatusForbidden, "You do not have access to this report", nil)
		return
	}

	// 6️⃣ Add comment
	comment := &models.WeeklyReportComment{
		ReportID:  report.ID,
		UserID:    user.UserID,
		Comment:   input.Comment,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	if err := c.DB.Create(comment).Error; err != nil {
		c.Json(w, http.StatusInternalServerError, "Failed to add comment", map[string]interface{}{
			"error": err.Error(),
		})
		return
	}

	// 7️⃣ Notify report owner if commenter is not the owner
	if report.StudentID != user.UserID {
		c.NotifyAndTrack(
			report.StudentID,
			"New Comment on Your Weekly Report",
			fmt.Sprintf("%s commented: %s", user.Username, input.Comment),
			"Weekly Report Comment",
			"WeeklyReport",
			&report.ID,
			"",
		)
	}

	// 8️⃣ Fetch all comments for this report
	var comments []models.WeeklyReportComment
	c.DB.Preload("User").Where("report_id = ?", report.ID).Find(&comments)

	// 9️⃣ Return response
	c.Json(w, http.StatusOK, "Comment added successfully", map[string]interface{}{
		"report":   report,
		"comments": comments,
	})
}

// UserHasCohortAccess checks if a user belongs to a cohort

func (c *Construct) UserHasCohortAccess(userID, cohortID uint64) bool {
	var count int64
	c.DB.Model(&models.CohortUser{}).
		Where("user_user_id = ? AND cohort_cohort_id = ?", userID, cohortID).
		Count(&count)
	return count > 0
}

// getting weekly reports

func (c *Construct) GetWeeklyReports(w http.ResponseWriter, r *http.Request) {
	user, err := c.GetAuthenticatedUser(r)
	if err != nil {
		c.Json(w, http.StatusUnauthorized, "Unauthorized", nil)
		return
	}

	var reports []models.WeeklyReport
	query := c.DB.Preload("Student.Profile").
		Preload("Student.Role").
		Preload("ReviewedBy.Profile").
		Preload("Cohort").
		Preload("LinkedItem.Entity").
		Preload("Comments.User.Profile"). // ✅ Preload comments with user info
		Order("created_at DESC")

	switch user.Role.Name {
	case "Student":
		// ✅ Student sees all reports from students in their cohort(s)
		var cohortIDs []uint64
		c.DB.Table("cohort_students").
			Select("cohort_id").
			Where("student_id = ?", user.UserID).
			Scan(&cohortIDs)

		if len(cohortIDs) == 0 {
			c.Json(w, http.StatusOK, "No reports available", map[string]interface{}{
				"data": []models.WeeklyReport{},
			})
			return
		}

		query = query.Where("cohort_id IN ?", cohortIDs)

	case "Mentor", "Supervisor":
		// ✅ Mentors/Supervisors see reports from assigned cohorts
		cohortIDs := c.getAssignCohorts(user.UserID, user.Role.Name)
		if len(cohortIDs) == 0 {
			c.Json(w, http.StatusOK, "No assigned cohorts found", map[string]interface{}{
				"data": []models.WeeklyReport{},
			})
			return
		}

		query = query.Where("cohort_id IN ?", cohortIDs)

	case "OpsAdmin", "SystemAdmin":
		// ✅ Admins see all reports, no additional filters

	default:
		c.Json(w, http.StatusForbidden, "Unauthorized role", nil)
		return
	}

	// 📦 Fetch reports
	if err := query.Find(&reports).Error; err != nil {
		c.Json(w, http.StatusInternalServerError, "Failed to fetch reports", map[string]interface{}{
			"error": err.Error(),
		})
		return
	}

	// 📢 Track viewing action
	c.NotifyAndTrack(
		user.UserID,
		"Viewed Weekly Reports",
		fmt.Sprintf("%s viewed weekly reports list", user.Username),
		"Read",
		"WeeklyReport",
		nil,
		"Viewed",
	)

	c.Json(w, http.StatusOK, "Weekly reports fetched successfully", map[string]interface{}{
		"data": reports,
	})
}

// deleting, archiving, or unarchiving reports

func (c *Construct) ManageWeeklyReports(w http.ResponseWriter, r *http.Request) {
	// Parse input
	var input struct {
		ReportIDs []uint64 `json:"report_ids"`
		Action    string   `json:"action"` // "archive", "unarchive", "delete"
	}

	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
		c.Json(w, http.StatusBadRequest, "Invalid request body", nil)
		return
	}

	if len(input.ReportIDs) == 0 || input.Action == "" {
		c.Json(w, http.StatusBadRequest, "report_ids and action are required", nil)
		return
	}

	user, err := c.GetAuthenticatedUser(r)
	if err != nil {
		c.Json(w, http.StatusUnauthorized, "Unauthorized", nil)
		return
	}

	var reports []models.WeeklyReport
	if err := c.DB.Where("id IN ?", input.ReportIDs).Find(&reports).Error; err != nil {
		c.Json(w, http.StatusInternalServerError, "Failed to fetch reports", map[string]interface{}{"error": err.Error()})
		return
	}

	if len(reports) == 0 {
		c.Json(w, http.StatusNotFound, "No reports found for the given IDs", nil)
		return
	}

	for _, report := range reports {
		switch input.Action {
		case "archive":
			if user.Role.Name != "Supervisor" && user.Role.Name != "OpsAdmin" && user.Role.Name != "SystemAdmin" {
				c.Json(w, http.StatusForbidden, "Only supervisors/admins can archive reports", nil)
				return
			}
			report.IsArchived = true
			report.UpdatedAt = time.Now()
			c.DB.Save(&report)
			c.NotifyAndTrack(user.UserID, "Weekly Report Archived",
				fmt.Sprintf("Weekly report #%d was archived", report.ID),
				"Weekly Report Archive", "WeeklyReport", &report.ID, "Archived",
			)

		case "unarchive":
			if user.Role.Name != "Supervisor" && user.Role.Name != "OpsAdmin" && user.Role.Name != "SystemAdmin" {
				c.Json(w, http.StatusForbidden, "Only supervisors/admins can unarchive reports", nil)
				return
			}
			report.IsArchived = false
			report.UpdatedAt = time.Now()
			c.DB.Save(&report)
			c.NotifyAndTrack(user.UserID, "Weekly Report Unarchived",
				fmt.Sprintf("Weekly report #%d was unarchived", report.ID),
				"Weekly Report Unarchive", "WeeklyReport", &report.ID, "Unarchived",
			)

		case "delete":
			if user.Role.Name == "Student" {
				if report.StudentID != user.UserID {
					c.Json(w, http.StatusForbidden, "You can only delete your own reports", nil)
					return
				}
				// Students “soft delete” = archive
				report.IsArchived = true
				report.UpdatedAt = time.Now()
				c.DB.Save(&report)
				c.NotifyAndTrack(user.UserID, "Weekly Report Archived",
					fmt.Sprintf("You archived your weekly report #%d", report.ID),
					"Weekly Report Archive", "WeeklyReport", &report.ID, "Archived",
				)
			} else if user.Role.Name == "Supervisor" || user.Role.Name == "OpsAdmin" || user.Role.Name == "SystemAdmin" {
				c.DB.Unscoped().Delete(&report)
				c.NotifyAndTrack(user.UserID, "Weekly Report Deleted Permanently",
					fmt.Sprintf("Weekly report #%d was permanently deleted", report.ID),
					"Weekly Report Deletion", "WeeklyReport", &report.ID, "Deleted",
				)
			} else {
				c.Json(w, http.StatusForbidden, "You do not have permission to delete this report", nil)
				return
			}

		default:
			c.Json(w, http.StatusBadRequest, "Invalid action, must be 'archive', 'unarchive', or 'delete'", nil)
			return
		}
	}

	c.Json(w, http.StatusOK, fmt.Sprintf("Action '%s' performed on selected reports successfully", input.Action), nil)
}
