package models

import (
	"time"

	"gorm.io/gorm"
)

// Status options for entity or item
const (
	StatusPending    = "Pending"
	StatusInProgress = "In Progress"
	StatusCompleted  = "Completed"
	StatusArchived   = "Archived"
)
const (
	VerifiedStatusPendingVerification = "Pending Verification"
	VerifiedStatusVerified            = "Verified"
	VerifiedStatusRejected            = "Rejected"
)

// ProgressType options
const (
	ProgressTypeMilestone  = "Milestone"
	ProgressTypeTask       = "Task"
	ProgressTypeAssessment = "Assessment"
)

// report status options
// WeeklyReport status options
// WeeklyReport status options
const (
	StatusPendingVerification = "Pending Verification" // default when student submits
	StatusApproved            = "Approved"             // supervisor approves
	StatusSendBack            = "Send Back"            // supervisor sends back for revision
)

type ProgressEntity struct {
	ID             uint64  `gorm:"primaryKey;autoIncrement" json:"id"`
	EntityCohortID *uint64 `gorm:"index" json:"cohort_id"`
	EntityCohort   *Cohort `gorm:"foreignKey:EntityCohortID;references:CohortID" json:"cohort_profile,omitempty"`

	AssignedToID *uint64 `gorm:"index" json:"assigned_to_id,omitempty"`
	AssignedTo   *User   `gorm:"foreignKey:AssignedToID;references:UserID" json:"assigned_to,omitempty"`

	EntityName   string         `gorm:"size:255;not null" json:"entity_name"`       // e.g. "Cohort_2025"
	EntityType   string         `gorm:"size:100;not null;index" json:"entity_type"` // e.g. "Cohort", "Proposal", "Event"
	Status       string         `gorm:"size:50;not null;default:'Pending'" json:"status"`
	Performance  float64        `gorm:"default:0" json:"performance"`
	ProgressType string         `gorm:"size:100;default:'Milestone'" json:"progress_type,omitempty"` // e.g. milestone, task, assessment
	Metadata     *string        `gorm:"type:jsonb" json:"metadata,omitempty"`
	IsArchived   bool           `gorm:"default:false" json:"is_archived"`
	CreatedAt    time.Time      `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"autoUpdateTime" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"index" json:"-"`

	// Relationships
	Items []ProgressItem `gorm:"foreignKey:ProgressEntityRefID" json:"items,omitempty"`
}

// progress items for tracking
type ProgressItem struct {
	ID                  uint64          `gorm:"primaryKey;autoIncrement" json:"id"`
	CohortRefID         *uint64         `gorm:"index;constraint:OnDelete:SET NULL;" json:"cohort_ref_id,omitempty"`
	CohortProfile       *Cohort         `gorm:"foreignKey:CohortRefID;references:CohortID" json:"cohort_profile,omitempty"`
	ProgressEntityRefID *uint64         `gorm:"not null;index;constraint:OnDelete:CASCADE;" json:"entity_id"`
	ProgressEntityRef   *ProgressEntity `gorm:"foreignKey:ProgressEntityRefID;references:ID" json:"progress_entity,omitempty"`

	ParentID     *uint64 `gorm:"index" json:"parent_id,omitempty"`
	PhaseName    string  `gorm:"size:255;not null" json:"phase_name"`
	ProgressType string  `gorm:"size:100;default:'Milestone'" json:"progress_type,omitempty"`

	// 🔹 Dual-status system
	StudentStatus  string `gorm:"size:50;not null;default:'Pending'" json:"student_status"`               // student's progress state
	VerifiedStatus string `gorm:"size:50;not null;default:'Pending Verification'" json:"verified_status"` // supervisor's verification

	Weight      float64    `gorm:"default:0" json:"weight"`
	Performance float64    `gorm:"default:0" json:"performance"`
	DueDate     *time.Time `json:"due_date,omitempty"`
	CompletedAt *time.Time `json:"completed_at,omitempty"`

	AssignedToID *uint64 `gorm:"index" json:"assigned_to_id,omitempty"`
	AssignedTo   *User   `gorm:"foreignKey:AssignedToID;references:UserID" json:"assigned_to,omitempty"`

	CreatedByID uint64 `gorm:"index;not null" json:"created_by_id"`
	CreatedBy   *User  `gorm:"foreignKey:CreatedByID;references:UserID" json:"created_by,omitempty"`

	Metadata   *string        `gorm:"type:jsonb" json:"metadata,omitempty"`
	IsArchived bool           `gorm:"default:false" json:"is_archived"`
	CreatedAt  time.Time      `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"autoUpdateTime" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"index" json:"-"`

	WeeklyReports []*WeeklyReport `gorm:"many2many:weekly_report_progress_items;joinForeignKey:ProgressItemID;joinReferences:WeeklyReportID" json:"weekly_reports,omitempty"`
	TeamRefID     *uint64         `gorm:"index;constraint:OnDelete:SET NULL;" json:"team_ref_id,omitempty"`
	TeamDetails   *Team           `gorm:"foreignKey:TeamRefID;references:TeamID" json:"team_details,omitempty"`
}

// reports generated by students

type WeeklyReport struct {
	ID               uint64  `gorm:"primaryKey;autoIncrement" json:"id"`
	ReportCohortID   *uint64 `gorm:"index;not null" json:"report_cohort_id"`
	ReportCohortInfo *Cohort `gorm:"foreignKey:ReportCohortID;references:CohortID" json:"report_cohort_info,omitempty"`

	StudentID uint64 `gorm:"index;not null" json:"student_id"`
	Student   User   `gorm:"foreignKey:StudentID;references:UserID" json:"student,omitempty"`

	WeekStart   time.Time `gorm:"not null" json:"week_start"`
	WeekEnd     time.Time `gorm:"not null" json:"week_end"`
	WorkDone    string    `gorm:"type:text" json:"work_done"`
	PlannedWork string    `gorm:"type:text" json:"planned_work"`
	NextWeek    string    `gorm:"type:text" json:"next_week"`
	Challenges  string    `gorm:"type:text" json:"challenges"`
	Status      string    `gorm:"size:50;default:'Pending Verification'" json:"status"`

	ReviewedByID *uint64 `gorm:"index" json:"reviewed_by_id,omitempty"`
	ReviewedBy   *User   `gorm:"foreignKey:ReviewedByID;references:UserID" json:"reviewed_by,omitempty"`
	DocumentURL  *string `gorm:"type:text" json:"document_url,omitempty"` // 🔹 File upload URL (PDF, CSV)

	TeamInfoID *uint64 `gorm:"index" json:"team_id,omitempty"`
	TeamInfo   *Team   `gorm:"foreignKey:TeamInfoID;references:TeamID" json:"team_info,omitempty"`

	TeamLeaderReportID *uint64       `json:"team_leader_report_id,omitempty"`
	TeamLeaderReport   *WeeklyReport `gorm:"foreignKey:TeamLeaderReportID;references:ID" json:"team_leader_report,omitempty"`

	IsArchived bool           `gorm:"default:false" json:"is_archived"`
	CreatedAt  time.Time      `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"autoUpdateTime" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"index" json:"-"`

	// Many-to-many relationship
	ProgressItems []*ProgressItem       `gorm:"many2many:weekly_report_progress_items;" json:"progress_items,omitempty"`
	Comments      []WeeklyReportComment `gorm:"foreignKey:WeeklyReportRefID;references:ID" json:"comments,omitempty"`
}

// weekly report comments

type WeeklyReportComment struct {
	ID                uint64        `gorm:"primaryKey;autoIncrement" json:"id"`
	WeeklyReportRefID *uint64       `gorm:"index" json:"weekly_report_ref_id"`
	WeeklyReportInfo  *WeeklyReport `gorm:"foreignKey:WeeklyReportRefID;references:ID" json:"weekly_report_info,omitempty"`
	ParentID          *uint64       `gorm:"index" json:"parent_id,omitempty"`

	EditedByID *uint64 `gorm:"index" json:"edited_by_id,omitempty"`
	EditedBy   *User   `gorm:"foreignKey:EditedByID;references:UserID" json:"edited_by,omitempty"`

	Comment   string    `gorm:"type:text" json:"comment"`
	CreatedAt time.Time `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt time.Time `gorm:"autoUpdateTime" json:"updated_at"`
}

// mentor feedback

type MentorFeedback struct {
	ID       uint64 `gorm:"primaryKey;autoIncrement"`
	MentorID uint64 `gorm:"index;not null"`                                      // who gave the feedback
	Mentor   User   `gorm:"foreignKey:MentorID;references:UserID" json:"mentor"` // preload mentor info

	MentorReportID      *uint64       `gorm:"index" json:"mentor_report_id,omitempty"`
	MentorReportProfile *WeeklyReport `gorm:"foreignKey:MentorReportID;references:ID" json:"mentor_report_profile,omitempty"`

	ItemID *uint64       `gorm:"index" json:"item_id,omitempty"`                        // feedback on specific item
	Item   *ProgressItem `gorm:"foreignKey:ItemID;references:ID" json:"item,omitempty"` // optional: preload item info

	Comment        string   `gorm:"type:text" json:"comment"`
	Rating         *float64 `json:"rating,omitempty"`
	Recommendation string   `gorm:"type:text" json:"recommendation"`

	IsPublic  bool   `gorm:"default:false" json:"is_public"`
	StudentID uint64 `gorm:"index;not null" json:"student_id"`
	Student   User   `gorm:"foreignKey:StudentID;references:UserID" json:"student"`

	// ✅ new fields to link feedback to cohort
	MentorCohortID uint64  `gorm:"index;not null" json:"mentor_cohort_id"`
	MentorCohort   *Cohort `gorm:"foreignKey:MentorCohortID;references:CohortID" json:"mentor_cohort,omitempty"`

	IsArchived bool           `gorm:"default:false" json:"is_archived"`
	CreatedAt  time.Time      `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"autoUpdateTime" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"index" json:"-"`
}
