package models

import (
	"time"

	"gorm.io/gorm"
)

// Status options for entity or item
const (
	StatusPending    = "Pending"
	StatusInProgress = "In Progress"
	StatusCompleted  = "Completed"
	StatusArchived   = "Archived"
)

// ProgressType options
const (
	ProgressTypeMilestone  = "Milestone"
	ProgressTypeTask       = "Task"
	ProgressTypeAssessment = "Assessment"
)

// report status options
const (
	StatusReviewed = "Reviewed"
	StatusActioned = "Actioned"
	StatusRejected = "Rejected"
)

type ProgressEntity struct {
	ID           uint64  `gorm:"primaryKey;autoIncrement" json:"id"`
	CohortID     *uint64 `gorm:"index;constraint:OnDelete:SET NULL;" json:"cohort_id,omitempty"`
	Cohort       *Cohort `gorm:"foreignKey:CohortID;references:CohortID" json:"cohort,omitempty"`
	AssignedToID *uint64 `gorm:"index" json:"assigned_to_id,omitempty"`
	AssignedTo   *User   `gorm:"foreignKey:AssignedToID;references:UserID" json:"assigned_to,omitempty"`

	EntityName   string         `gorm:"size:255;not null" json:"entity_name"`       // e.g. "Cohort_2025"
	EntityType   string         `gorm:"size:100;not null;index" json:"entity_type"` // e.g. "Cohort", "Proposal", "Event"
	Status       string         `gorm:"size:50;not null;default:'Pending'" json:"status"`
	Performance  float64        `gorm:"default:0" json:"performance"`
	ProgressType string         `gorm:"size:100;default:'Milestone'" json:"progress_type,omitempty"` // e.g. milestone, task, assessment
	Metadata     *string        `gorm:"type:jsonb" json:"metadata,omitempty"`
	IsArchived   bool           `gorm:"default:false" json:"is_archived"`
	CreatedAt    time.Time      `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"autoUpdateTime" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"index" json:"-"`

	// Relationships
	Items []ProgressItem `gorm:"foreignKey:EntityID" json:"items,omitempty"`
}

// progress items for tracking
type ProgressItem struct {
	ID       uint64          `gorm:"primaryKey;autoIncrement" json:"id"`
	CohortID *uint64         `gorm:"index;constraint:OnDelete:SET NULL;" json:"cohort_id,omitempty"`
	Cohort   *Cohort         `gorm:"foreignKey:CohortID;references:CohortID" json:"cohort,omitempty"`
	EntityID uint64          `gorm:"not null;index;constraint:OnDelete:CASCADE;" json:"entity_id"`
	Entity   *ProgressEntity `gorm:"foreignKey:EntityID;references:ID" json:"entity,omitempty"`

	ParentID     *uint64    `gorm:"index" json:"parent_id,omitempty"`
	PhaseName    string     `gorm:"size:255;not null" json:"phase_name"`
	ProgressType string     `gorm:"size:100;default:'Milestone'" json:"progress_type,omitempty"`
	Status       string     `gorm:"size:50;not null;default:'Pending'" json:"status"`
	Weight       float64    `gorm:"default:0" json:"weight"`
	Performance  float64    `gorm:"default:0" json:"performance"`
	DueDate      *time.Time `json:"due_date,omitempty"`
	CompletedAt  *time.Time `json:"completed_at,omitempty"`
	AssignedToID *uint64    `gorm:"index" json:"assigned_to_id,omitempty"`                                  // FK column
	AssignedTo   *User      `gorm:"foreignKey:AssignedToID;references:UserID" json:"assigned_to,omitempty"` // Relationship
	CreatedByID  uint64     `gorm:"index;not null" json:"created_by_id"`
	CreatedBy    *User      `gorm:"foreignKey:CreatedByID;references:UserID" json:"created_by,omitempty"`

	Metadata   *string        `gorm:"type:jsonb" json:"metadata,omitempty"`
	IsArchived bool           `gorm:"default:false" json:"is_archived"`
	CreatedAt  time.Time      `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"autoUpdateTime" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"index" json:"-"`

	WeeklyReports []*WeeklyReport `gorm:"many2many:weekly_report_progress_items;joinForeignKey:ProgressItemID;joinReferences:WeeklyReportID" json:"weekly_reports,omitempty"`
}

// reports generated by students

type WeeklyReport struct {
	ID       uint64  `gorm:"primaryKey;autoIncrement" json:"id"`
	CohortID *uint64 `gorm:"index;not null" json:"cohort_id"`
	Cohort   *Cohort `gorm:"foreignKey:CohortID;references:CohortID" json:"cohort,omitempty"`

	StudentID uint64 `gorm:"index;not null" json:"student_id"`
	Student   User   `gorm:"foreignKey:StudentID;references:UserID" json:"student,omitempty"`

	WeekStart   time.Time `gorm:"not null" json:"week_start"`
	WeekEnd     time.Time `gorm:"not null" json:"week_end"`
	WorkDone    string    `gorm:"type:text" json:"work_done"`
	PlannedWork string    `gorm:"type:text" json:"planned_work"`
	NextWeek    string    `gorm:"type:text" json:"next_week"`
	Challenges  string    `gorm:"type:text" json:"challenges"`
	Status      string    `gorm:"size:50;default:'Pending'" json:"status"`

	ReviewedByID *uint64 `gorm:"index" json:"reviewed_by_id,omitempty"`
	ReviewedBy   *User   `gorm:"foreignKey:ReviewedByID;references:UserID" json:"reviewed_by,omitempty"`

	IsArchived bool           `gorm:"default:false" json:"is_archived"`
	CreatedAt  time.Time      `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"autoUpdateTime" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"index" json:"-"`

	// Many-to-many relationship
	ProgressItems []*ProgressItem `gorm:"many2many:weekly_report_progress_items;" json:"progress_items,omitempty"`
}

// weekly report comments

type WeeklyReportComment struct {
	ID       uint64        `gorm:"primaryKey;autoIncrement" json:"id"`
	ReportID uint64        `gorm:"index;not null;constraint:OnUpdate:CASCADE,OnDelete:CASCADE" json:"report_id"`
	Report   *WeeklyReport `gorm:"foreignKey:ReportID;references:ID" json:"report,omitempty"`
	ParentID *uint64       `gorm:"index" json:"parent_id,omitempty"`

	UserID uint64 `gorm:"index;not null;constraint:OnUpdate:CASCADE,OnDelete:CASCADE" json:"user_id"`
	User   *User  `gorm:"foreignKey:UserID;references:UserID" json:"user,omitempty"`

	Comment   string    `gorm:"type:text" json:"comment"`
	CreatedAt time.Time `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt time.Time `gorm:"autoUpdateTime" json:"updated_at"`
}

// supervisor status enforcements model
type SupervisorEnforcement struct {
	ID       uint64        `gorm:"primaryKey;autoIncrement" json:"id"`
	ReportID uint64        `gorm:"index;not null" json:"report_id"` // the weekly report that triggered the enforcement
	Report   *WeeklyReport `gorm:"foreignKey:ReportID;references:ID" json:"report,omitempty"`

	ProgressItemID uint64        `gorm:"index;not null" json:"progress_item_id"` // affected item
	ProgressItem   *ProgressItem `gorm:"foreignKey:ProgressItemID;references:ID" json:"progress_item,omitempty"`

	EnforcedByID uint64 `gorm:"index;not null" json:"enforced_by_id"` // supervisor user ID
	EnforcedBy   *User  `gorm:"foreignKey:EnforcedByID;references:UserID" json:"enforced_by,omitempty"`

	OldStatus string `gorm:"size:50;not null" json:"old_status"` // previous status of the item
	NewStatus string `gorm:"size:50;not null" json:"new_status"` // enforced status

	Reason    string    `gorm:"type:text" json:"reason"` // optional explanation
	CreatedAt time.Time `gorm:"autoCreateTime" json:"created_at"`
}
